### ISSUE TITLE
Announcement

### ISSUE THREAD

**Issue by wimjongman** [eclipse/birt-website#34]
The announcement was done in the wrong branch.

**Comment by wimjongman** [comment]
@chloetz please try again

**Comment by wimjongman** [comment]
<p> </p>
          
          <p className="hero__title">
          Good news !
          </p>

          <p className="hero__subtitle">
          The BIRT project has picked up again and a new release 4.9.0 is available.<br/>
          The goal of this release is to make BIRT run with newer versions of Java (requires Java 11)<br/>
          and to fix some long outstanding bugs.<br/><br/> 
          Your help is welcome on our adventure into the future !
          </p>
         <p></p>

**Comment by minduch** [comment]
Is this project still alive? The website seems very outdated with mostly broken links.

**Comment by chloetz** [comment]
You might get that impression, but it's not so.
Lately, and certainly for the next few months, I've been busy organizing the Covid-related gaps in the company.
As soon as calm returns, I will be back.


Von: Christopher Mindus ***@***.***
Gesendet: Montag, 8. August 2022 16:09
An: eclipse/birt-website
Cc: Loetz, Christophe; Mention
Betreff: Re: [eclipse/birt-website] Announcement (Issue #34)


Is this project still alive? The website seems very outdated with mostly broken links.

**Comment by wimjongman** [comment]
No action. Closing.
