### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by benharvie** [eclipse/birt-website#38]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@youssef1313) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by wimjongman** [comment]
Hi @benharvie. Sorry for the delay, and thanks for helping!!

@waynebeaton is there a process in place for this?

**Comment by Youssef1313** [comment]
@wimjongman @waynebeaton Any updates?

**Comment by wimjongman** [comment]
I searched on eclipse and found [https://www.eclipse.org/security/policy.php](https://www.eclipse.org/security/policy.php)

**Comment by wimjongman** [comment]
> I searched on eclipse and found https://www.eclipse.org/security/policy.php

and this [https://www.eclipse.org/security/](https://www.eclipse.org/security/)

**Comment by Youssef1313** [comment]
Closing as SECURITY.md is now added https://github.com/eclipse/birt-website/security
